package cux.oracle.apps.ap.oie.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImportExcelVORowImpl extends OAViewRowImpl {
    public static final int FILENAME = 0;
    public static final int FILECONTEXT = 1;

    /**This is the default constructor (do not remove)
     */
    public ImportExcelVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Filename
     */
    public String getFilename() {
        return (String) getAttributeInternal(FILENAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Filename
     */
    public void setFilename(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**Gets the attribute value for the calculated attribute Filecontext
     */
    public BlobDomain getFilecontext() {
        return (BlobDomain) getAttributeInternal(FILECONTEXT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Filecontext
     */
    public void setFilecontext(BlobDomain value) {
        setAttributeInternal(FILECONTEXT, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case FILENAME:
            return getFilename();
        case FILECONTEXT:
            return getFilecontext();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case FILENAME:
            setFilename((String)value);
            return;
        case FILECONTEXT:
            setFilecontext((BlobDomain)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
